### ISSUE TITLE
2022.07.0 error

### ISSUE THREAD

**Issue by CrallH** [Miicroo/ha-swedish_calendar#12]
Updated to latest HA and got this:
Logger: homeassistant.components.sensor
Source: custom_components/swedish_calendar/sensor.py:281
Integration: Sensor (documentation, issues)
First occurred: 22:17:06 (1 occurrences)
Last logged: 22:17:06

Error while setting up swedish_calendar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/swedish_calendar/sensor.py", line 65, in async_setup_platform
    await themeSensor.fetching_data()
  File "/config/custom_components/swedish_calendar/sensor.py", line 281, in fetching_data
    await asyncio.wait(tasks, loop=self.hass.loop)
TypeError: wait() got an unexpected keyword argument 'loop'

**Comment by Miicroo** [comment]
@CrallH Super, thanks for the heads up! Pushed a fix now that removes the deprecated loop keyword. Let me know if it works and Ill close the issue :)

**Comment by CrallH** [comment]
> @CrallH Super, thanks for the heads up! Pushed a fix now that removes the deprecated loop keyword. Let me know if it works and Ill close the issue :)

It worked
