### ISSUE TITLE
0.112.0 crashed swedish calendar

### ISSUE THREAD

**Issue by CrallH** [Miicroo/ha-swedish_calendar#2]
After the last HA update 0.112.0 i only get this in the log.

`Logginformation (ERROR)
Logger: homeassistant.components.sensor
Source: helpers/event.py:252
Integration: Sensor (documentation, issues)
First occurred: 21:21:41 (1 occurrences)
Last logged: 21:21:41

Error while setting up swedish_calendar platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/swedish_calendar/sensor.py", line 65, in async_setup_platform
    await themeSensor.fetching_data()
  File "/config/custom_components/swedish_calendar/sensor.py", line 282, in fetching_data
    async_call_later(self.hass, get_seconds_until_midnight(), self.fetching_data)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 267, in async_call_later
    hass, action, dt_util.utcnow() + timedelta(seconds=delay)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 252, in async_track_point_in_utc_time
    async_unsub = hass.bus.async_listen(EVENT_TIME_CHANGED, point_in_time_listener)
AttributeError: 'NoneType' object has no attribute 'bus'`

**Comment by CrallH** [comment]
Upgraded to 0.112.1 solved it

**Comment by CrallH** [comment]
0.112.4 gives the same error.

**Comment by Miicroo** [comment]
Should be fixed now, seems OK based on comments on HA community 👍
