### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by djungelola** [Miicroo/ha-swedish_calendar#27]
Hi

Hi
After upgrading to 2.3.0 i get below error when validating my YAML.
In configuration.yaml:
swedish_calendar:

Downgrading to 2.2.1 it works just fine with same configuration.

2022-11-14 20:44:55.408 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.swedish_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/swedish_calendar/__init__.py", line 106
    if deprecated_themes_path:
IndentationError: unexpected indent

**Comment by Miicroo** [comment]
Oooops, my bad! Thought I had pushed the last commit that included a fix but must have missed. Released 2.3.1 and included the correctly re-indented line

**Comment by Miicroo** [comment]
@djungelola Thank you for the report! Really appreciate it!

**Comment by djungelola** [comment]
Bara kul att kunna hjälpa till med något :-)

**Comment by djungelola** [comment]
Works fine, can be closed!
